const todo =[
  //TODO { icon: { name: 'postcss' }, ids: ['postcss'] },

  { icon: { name: 'matlab' }, ids: ['matlab'] },
  { icon: { name: 'blink' }, ids: ['blink'] },
  { icon: { name: 'scala' }, ids: ['scala'] },
  { icon: { name: 'haxe' }, ids: ['haxe', 'hxml'] },
  { icon: { name: 'puppet' }, ids: ['puppet'] },
  { icon: { name: 'livescript' }, ids: ['livescript'] },
  { icon: { name: 'twig' }, ids: ['twig'] },
  { icon: { name: 'purescript' }, ids: ['purescript'] },
  { icon: { name: 'stylus' }, ids: ['stylus'] },
  { icon: { name: 'nunjucks' }, ids: ['nunjucks'] },
  { icon: { name: 'robot' }, ids: ['robotframework'] },
  { icon: { name: 'solidity' }, ids: ['solidity'] },
  { icon: { name: 'autoit' }, ids: ['autoit'] },
  { icon: { name: 'haml' }, ids: ['haml'] },
  { icon: { name: 'yang' }, ids: ['yang'] },
  { icon: { name: 'terraform' }, ids: ['terraform'] },
  { icon: { name: 'applescript' }, ids: ['applescript'] },
  { icon: { name: 'cake' }, ids: ['cake'] },
  { icon: { name: 'nim' }, ids: ['nim', 'nimble'] },
  { icon: { name: 'apiblueprint' }, ids: ['apiblueprint'] },
  { icon: { name: 'riot' }, ids: ['riot'] },
  { icon: { name: 'coldfusion' }, ids: ['lang-cfml'] },
  { icon: { name: 'dhall' }, ids: ['dhall'] },
  { icon: { name: 'cabal' }, ids: ['cabal'] },
  { icon: { name: 'nix' }, ids: ['nix'] },
  { icon: { name: 'slim' }, ids: ['slim'] },
  { icon: { name: 'hack' }, ids: ['hack'] },
  { icon: { name: 'mjml' }, ids: ['mjml'] },
  { icon: { name: 'processing' }, ids: ['processing'] },
  { icon: { name: 'hcl' }, ids: ['hcl'] },
  { icon: { name: 'django' }, ids: ['django-html', 'django-txt'] },
  { icon: { name: 'godot' }, ids: ['gdscript'] },
  { icon: { name: 'vim' }, ids: ['viml'] },
  { icon: { name: 'silverstripe' }, ids: [] },
  { icon: { name: 'prolog' }, ids: ['prolog'] },
  { icon: { name: 'pawn' }, ids: ['pawn'] },
  { icon: { name: 'sml' }, ids: ['sml'] },
  { icon: { name: 'salesforce' }, ids: ['apex'] },
  { icon: { name: 'sas' }, ids: ['sas'] },
  { icon: { name: 'jinja' }, ids: ['jinja'] },
  { icon: { name: 'proto' }, ids: ['proto'] },
  { icon: { name: 'python-misc' }, ids: ['pip-requirements'] },
  { icon: { name: 'jupyter' }, ids: ['jupyter'] },
  { icon: { name: 'kusto' }, ids: ['kql'] },
  { icon: { name: 'lock' }, ids: ['ssh_config'] },
  { icon: { name: 'minecraft' }, ids: ['mcfunction'] },
  { icon: { name: 'otne' }, ids: ['otne'] },
  { icon: { name: 'twine' }, ids: ['twee3', 'twee3-harlowe-3', 'twee3-chapbook-1', 'twee3-sugarcube-2'] },
  { icon: { name: 'grain' }, ids: ['grain'] },
  { icon: { name: 'lolcode' }, ids: ['lolcode'] },
  { icon: { name: 'idris' }, ids: ['idris'] },
  { icon: { name: 'chess' }, ids: ['pgn'] },
  { icon: { name: 'gemini' }, ids: ['gemini', 'text-gemini'] },
  { icon: { name: 'wolframlanguage' }, ids: ['wolfram'] },
]
