export const extensions: IconMap = {
  bash: ['bash', 'sh', 'awk'],
  bat: ['bat'],
  c: ['c', 'i', 'mi'],
  csharp: ['cs', 'csx'],
  cpp: ['cc', 'cpp', 'cxx', 'c++', 'cp', 'mm', 'mii', 'ii'],
  docker: ['dockerfile', 'dockerignore'],
  dotenv: ['env'],
  dts: ['d.ts', 'd.cts', 'd.mts'],
  h: ['h'],
  hpp: ['hh', 'hpp', 'hxx', 'h++', 'hp', 'tcc', 'inl'],
  html: ['htm', 'xhtml', 'html_vm', 'asp'],
  java: ['java', 'jsp', 'class'],
  js: ['esx', 'cjs'],
  json: ['json', 'jsonc', 'json5', 'jsonl'],
  mapjs: ['js.map', 'cjs.map', 'mjs.map'],
  markdown: ['md', 'markdown'],
  pdf: ['pdf'],
  powershell: ['ps1', 'psm1', 'psd1', 'ps1xml', 'psc1', 'pssc'],
  properties: [
    'ini',
    'dlc',
    'dll',
    'config',
    'conf',
    'properties',
    'prop',
    'settings',
    'option',
    'props',
    'cfg',
    'prefs',
  ],
  rust: ['rs', 'ron'],
  sass: ['scss', 'sass'],
  spreadsheet: ['xlsx', 'xlsm', 'xls', 'csv', 'tsv', 'psv', 'ods'],
  svelte: ['svelte'],
  svg: ['svg'],
  text: ['txt'],
  toml: ['toml'],
  vlang: ['v'],
  xml: [
    'xml',
    'plist',
    'xsd',
    'dtd',
    'xsl',
    'xslt',
    'resx',
    'iml',
    'xquery',
    'tmLanguage',
    'manifest',
    'project',
    'xml.dist',
    'xml.dist.sample',
    'dmn',
  ],
  yaml: ['yml', 'yaml'],
}
