export const extensions: IconMap = {
  bash: ['bash', 'sh', 'awk'],
  bat: ['bat'],
  c: ['c', 'i', 'mi'],
  certificate: ['cer', 'cert', 'crt', 'pfx'],
  csharp: ['cs', 'csx'],
  cpp: ['cc', 'cpp', 'cxx', 'c++', 'cp', 'mm', 'mii', 'ii'],
  docker: ['dockerfile', 'dockerignore'],
  dotenv: ['env'],
  dts: ['d.ts', 'd.cts', 'd.mts'],
  h: ['h'],
  haskell: ['hs'],
  hpp: ['hh', 'hpp', 'hxx', 'h++', 'hp', 'tcc', 'inl'],
  html: ['htm', 'xhtml', 'html_vm', 'asp'],
  image: [
    'png',
    'jpeg',
    'jpg',
    'gif',
    'ico',
    'tif',
    'tiff',
    'psd',
    'psb',
    'ami',
    'apx',
    'avif',
    'bmp',
    'bpg',
    'brk',
    'cur',
    'dds',
    'dng',
    'exr',
    'fpx',
    'gbr',
    'img',
    'jbig2',
    'jb2',
    'jng',
    'jxr',
    'pgf',
    'pic',
    'raw',
    'webp',
    'eps',
    'afphoto',
    'ase',
    'aseprite',
    'clip',
    'cpt',
    'heif',
    'heic',
    'kra',
    'mdp',
    'ora',
    'pdn',
    'reb',
    'sai',
    'tga',
    'xcf',
    'jfif',
    'ppm',
    'pbm',
    'pgm',
    'pnm',
  ],
  java: ['java', 'jsp', 'class'],
  js: ['esx', 'cjs'],
  js_config: ['jsconfig.json'],
  json: ['json', 'jsonc', 'json5', 'jsonl'],
  key: ['pub', 'key', 'pem', 'asc', 'gpg', 'passwd'],
  mapjs: ['js.map', 'cjs.map', 'mjs.map'],
  markdown: ['md', 'markdown'],
  pdf: ['pdf'],
  powershell: ['ps1', 'psm1', 'psd1', 'ps1xml', 'psc1', 'pssc'],
  properties: [
    'ini',
    'dlc',
    'dll',
    'config',
    'conf',
    'properties',
    'prop',
    'settings',
    'option',
    'props',
    'cfg',
    'prefs',
  ],
  python: ['py'],
  python_alt: ['pyc', 'pyo', 'pyd'],
  rust: ['rs', 'ron'],
  sass: ['scss', 'sass'],
  spreadsheet: ['xlsx', 'xlsm', 'xls', 'csv', 'tsv', 'psv', 'ods'],
  svelte: ['svelte'],
  svg: ['svg'],
  test_js: [
    'spec.js',
    'spec.cjs',
    'spec.mjs',
    'e2e-spec.js',
    'e2e-spec.cjs',
    'e2e-spec.mjs',
    'test.js',
    'test.cjs',
    'test.mjs',
    'js.snap',
    'cy.js',
    'spec.jsx',
    'test.jsx',
    'jsx.snap',
    'cy.jsx',
  ],
  test_ts: [
    'spec.ts',
    'spec.cts',
    'spec.mts',
    'cy.ts',
    'e2e-spec.ts',
    'e2e-spec.cts',
    'e2e-spec.mts',
    'test.ts',
    'test.cts',
    'test.mts',
    'ts.snap',
    'spec.tsx',
    'test.tsx',
    'tsx.snap',
    'cy.tsx',
  ],
  text: ['txt'],
  toml: ['toml'],
  ts_config: ['tsconfig.json'],
  vlang: ['v'],
  xml: [
    'xml',
    'plist',
    'xsd',
    'dtd',
    'xsl',
    'xslt',
    'resx',
    'iml',
    'xquery',
    'tmLanguage',
    'manifest',
    'project',
    'xml.dist',
    'xml.dist.sample',
    'dmn',
  ],
  yaml: ['yml', 'yaml'],
}
