export const files: IconMap = {
  babel: [
    '.babelrc',
    '.babelrc.cjs',
    '.babelrc.js',
    '.babelrc.mjs',
    '.babelrc.json',
    'babel.config.cjs',
    'babel.config.js',
    'babel.config.mjs',
    'babel.config.json',
    'babel-transform.js',
    '.babel-plugin-macrosrc',
    '.babel-plugin-macrosrc.json',
    '.babel-plugin-macrosrc.yaml',
    '.babel-plugin-macrosrc.yml',
    '.babel-plugin-macrosrc.js',
    'babel-plugin-macros.config.js',
  ],
  bash: ['commit-msg', 'pre-commit', 'pre-push', 'post-merge'],
  browserslist: ['browserslist', '.browserslistrc'],
  cargo: ['Cargo.toml'],
  cargo_lock: ['Cargo.lock'],
  changelog: [
    'changelog',
    'changelog.md',
    'changelog.rst',
    'changelog.txt',
    'changes',
    'changes.md',
    'changes.rst',
    'changes.txt',
  ],
  code_of_conduct: [
    'code_of_conduct',
    'code_of_conduct.md',
    'code_of_conduct.rst',
    'code_of_conduct.txt',
  ],
  codeclimate: ['.codeclimate.yml'],
  codeowners: ['codeowners'],
  contributing: [
    'contributing',
    'contributing.md',
    'contributing.rst',
    'contributing.txt',
  ],
  cypress: [
    'cypress.json',
    'cypress.env.json',
    'cypress.config.ts',
    'cypress.config.js',
    'cypress.config.cjs',
    'cypress.config.mjs',
  ],
  dart: ['.pubignore'],
  docker: ['dockerfile', 'docker-compose.yml', 'docker-compose.yaml'],
  eslint: [
    '.eslintrc.js',
    '.eslintrc.cjs',
    '.eslintrc.yaml',
    '.eslintrc.yml',
    '.eslintrc.json',
    '.eslintrc-md.js',
    '.eslintrc-jsdoc.js',
    '.eslintrc',
  ],
  eslint_alt: ['.eslintignore', '.eslintcache'],
  git: [
    '.gitignore',
    '.gitconfig',
    '.gitattributes',
    '.gitmodules',
    '.gitkeep',
    '.git-include',
  ],
  gomod: ['go.mod'],
  gosum: ['go.sum'],
  graphql: [
    '.graphqlconfig',
    '.graphqlrc',
    '.graphqlrc.json',
    '.graphqlrc.js',
    '.graphqlrc.cjs',
    '.graphqlrc.ts',
    '.graphqlrc.toml',
    '.graphqlrc.yaml',
    '.graphqlrc.yml',
    'graphql.config.json',
    'graphql.config.js',
    'graphql.config.ts',
    'graphql.config.toml',
    'graphql.config.yaml',
    'graphql.config.yml',
  ],
  husky: [
    '.huskyrc',
    'husky.config.js',
    '.huskyrc.json',
    '.huskyrc.js',
    '.huskyrc.yaml',
    '.huskyrc.yml',
  ],
  jest: [
    'jest.config.js',
    'jest.config.cjs',
    'jest.config.mjs',
    'jest.config.ts',
    'jest.config.cts',
    'jest.config.mts',
    'jest.config.json',
    'jest.e2e.config.js',
    'jest.e2e.config.cjs',
    'jest.e2e.config.mjs',
    'jest.e2e.config.ts',
    'jest.e2e.config.cts',
    'jest.e2e.config.mts',
    'jest.e2e.config.json',
    'jest.e2e.json',
    'jest-unit.config.js',
    'jest-e2e.config.js',
    'jest-e2e.config.cjs',
    'jest-e2e.config.mjs',
    'jest-e2e.config.ts',
    'jest-e2e.config.cts',
    'jest-e2e.config.mts',
    'jest-e2e.config.json',
    'jest-e2e.json',
    'jest-github-actions-reporter.js',
    'jest.setup.js',
    'jest.setup.ts',
    'jest.json',
    '.jestrc',
    '.jestrc.js',
    '.jestrc.json',
    'jest.teardown.js',
  ],
  js_config: ['jsconfig.json'],
  license: [
    'copying',
    'copying.md',
    'copying.rst',
    'copying.txt',
    'copyright',
    'copyright.md',
    'copyright.rst',
    'copyright.txt',
    'license',
    'license-agpl',
    'license-apache',
    'license-bsd',
    'license-mit',
    'license-gpl',
    'license-lgpl',
    'license.md',
    'license.rst',
    'license.txt',
    'licence',
    'licence-agpl',
    'licence-apache',
    'licence-bsd',
    'licence-mit',
    'licence-gpl',
    'licence-lgpl',
    'licence.md',
    'licence.rst',
    'licence.txt',
  ],
  lua: ['.luacheckrc'],
  nest: [
    'nest-cli.json',
    '.nest-cli.json',
    'nestconfig.json',
    '.nestconfig.json',
  ],
  netlify: [
    'netlify.json',
    'netlify.yml',
    'netlify.yaml',
    'netlify.toml',
  ],
  nginx: ['nginx.conf'],
  npm: ['.npmrc', '.npmignore'],
  nuxt: ['nuxt.config.js', 'nuxt.config.ts', '.nuxtignore'],
  packagejson: ['package.json'],
  packagelock: ['package-lock.json', 'yarn.lock', 'pnpm-lock.yaml'],
  pnpm: ['.pnpmfile.cjs', 'pnpm-workspace.yaml'],
  prettier: [
    '.prettierrc',
    'prettier.config.js',
    'prettier.config.cjs',
    '.prettierrc.js',
    '.prettierrc.cjs',
    '.prettierrc.json',
    '.prettierrc.json5',
    '.prettierrc.yaml',
    '.prettierrc.yml',
    '.prettierignore',
    '.prettierrc.toml',
  ],
  pug: ['.pug-lintrc', '.pug-lintrc.js', '.pug-lintrc.json'],
  r: ['.Rhistory'],
  readme: ['readme.md', 'readme.rst', 'readme.txt', 'readme'],
  rollup: [
    'rollup.config.js',
    'rollup.config.ts',
    'rollup-config.js',
    'rollup-config.ts',
    'rollup.config.common.js',
    'rollup.config.common.ts',
    'rollup.config.base.js',
    'rollup.config.base.ts',
    'rollup.config.prod.js',
    'rollup.config.prod.ts',
    'rollup.config.dev.js',
    'rollup.config.dev.ts',
    'rollup.config.prod.vendor.js',
    'rollup.config.prod.vendor.ts',
  ],
  sonar: ['sonar-project.properties'],
  svelte: ['svelte.config.js', 'svelte.config.cjs'],
  ts_config: [
    'tsconfig.json',
    'tsconfig.app.json',
    'tsconfig.editor.json',
    'tsconfig.spec.json',
    'tsconfig.base.json',
    'tsconfig.build.json',
    'tsconfig.eslint.json',
    'tsconfig.lib.json',
    'tsconfig.node.json',
    'tsconfig.test.json',
    'tsconfig.config.json',
    'tsconfig.e2e.json',
    'tsconfig.vitest.json',
    'tsconfig.web.json',
    'tsconfig.webworker.json',
  ],
  unocss: ['unocss.config.js', 'unocss.config.ts'],
  vite: [
    'vite.config.js',
    'vite.config.mjs',
    'vite.config.cjs',
    'vite.config.ts',
    'vite.config.cts',
    'vite.config.mts',
    'vite.config.js',
    'vite.config.mjs',
    'vite.config.cjs',
    'vite.config.ts',
    'vite.config.cts',
    'vite.config.mts',
  ],
  vitest: [
    'vitest.config.js',
    'vitest.config.mjs',
    'vitest.config.cjs',
    'vitest.config.ts',
    'vitest.config.cts',
    'vitest.config.mts',
    'vitest.config.js',
    'vitest.config.mjs',
    'vitest.config.cjs',
    'vitest.config.ts',
    'vitest.config.cts',
    'vitest.config.mts',
  ],
  vlang: ['vpkg.json', 'v.mod'],
  vsutdio: [],
  vue_config: ['vue.config.js', 'vue.config.ts'],
  windi: [
    'windi.config.js',
    'windi.config.cjs',
    'windi.config.ts',
    'windi.config.cts',
    'windi.config.json',
  ]
}
