export const files: Record<string, string[]> = {
  bash: ['commit-msg', 'pre-commit', 'pre-push', 'post-merge'],
  cargo: ['Cargo.toml'],
  cargo_lock: ['Cargo.lock'],
  docker: ['dockerfile', 'docker-compose.yml', 'docker-compose.yaml'],
  git: ['.gitignore', '.gitconfig', '.gitattributes', '.gitmodules', '.gitkeep', '.git-include'],
  gomod: ['go.mod'],
  gosum: ['go.sum'],
  license: [
    'copying',
    'copying.md',
    'copying.rst',
    'copying.txt',
    'copyright',
    'copyright.md',
    'copyright.rst',
    'copyright.txt',
    'license',
    'license-agpl',
    'license-apache',
    'license-bsd',
    'license-mit',
    'license-gpl',
    'license-lgpl',
    'license.md',
    'license.rst',
    'license.txt',
    'licence',
    'licence-agpl',
    'licence-apache',
    'licence-bsd',
    'licence-mit',
    'licence-gpl',
    'licence-lgpl',
    'licence.md',
    'licence.rst',
    'licence.txt',
  ],
  packagejson: ['package.json'],
  packagelock: ['package-lock.json', 'yarn.lock', 'pnpm-lock.yaml'],
  svelte: ['svelte.config.js', 'svelte.config.cjs'],
  vlang: ['vpkg.json', 'v.mod']
}
