export const files: Record<string, string[]> = {
  cargo: ['Cargo.toml'],
  cargo_lock: ['Cargo.lock'],
  license: [
    'copying',
    'copying.md',
    'copying.rst',
    'copying.txt',
    'copyright',
    'copyright.md',
    'copyright.rst',
    'copyright.txt',
    'license',
    'license-agpl',
    'license-apache',
    'license-bsd',
    'license-mit',
    'license-gpl',
    'license-lgpl',
    'license.md',
    'license.rst',
    'license.txt',
    'licence',
    'licence-agpl',
    'licence-apache',
    'licence-bsd',
    'licence-mit',
    'licence-gpl',
    'licence-lgpl',
    'licence.md',
    'licence.rst',
    'licence.txt',
  ],
  packagejson: ['package.json'],
  packagelock: ['package-lock.json', 'yarn.lock', 'pnpm-lock.yaml'],
}
