export const languages: IconMap = {
  bash: ['awk', 'shellscript'],
  bat: ['bat'],
  c: ['c', 'objective-c', 'objective-cpp'],
  cpp: ['cpp'],
  csharp: ['csharp'],
  css: ['css', 'less', 'postcss'],
  docker: ['dockerfile'],
  editorconfig: ['editorconfig'],
  git: ['git', 'git-commit', 'git-rebase', 'ignore'],
  go: ['go'],
  haskell: ['haskell'],
  html: ['html'],
  java: ['java'],
  js: ['javascript'],
  json: ['json', 'jsonc', 'json5'],
  jsx: ['javascriptreact'],
  markdown: ['markdown'],
  pdf: ['pdf'],
  php: ['php'],
  powershell: ['powershell'],
  properties: ['makefile', 'ini', 'properties'],
  python: ['python'],
  rust: ['rust'],
  sass: ['sass', 'scss'],
  spreadsheet: ['csv', 'tsv', 'psv'],
  svelte: ['svelte'],
  svg: ['svg'],
  text: ['plaintext'],
  toml: ['toml'],
  ts: ['typescript'],
  tsx: ['typescriptreact'],
  vlang: ['v'],
  vue: ['vue', 'vue-postcss', 'vue-html'],
  xml: ['xml', 'xquery', 'xsl'],
  yaml: ['yaml']
}
