export const languages: IconMap = {
  bash: ['awk', 'shellscript'],
  bat: ['bat'],
  binary: ['code-text-binary'],
  c: ['c', 'objective-c', 'objective-cpp'],
  clojure: ['clojure'],
  coffee: ['coffeescript'],
  cpp: ['cpp'],
  csharp: ['csharp'],
  css: ['css', 'less', 'postcss'],
  cuda: ['cuda-cpp'],
  dart: ['dart'],
  diff: ['diff'],
  docker: ['dockerfile', 'dockercompose'],
  editorconfig: ['editorconfig'],
  fsharp: ['fsharp'],
  git: ['git', 'git-commit', 'git-rebase', 'ignore'],
  go: ['go'],
  graphql: ['graphql'],
  groovy: ['groovy'],
  handlebars: ['handlebars'],
  haskell: ['haskell'],
  html: ['html'],
  java: ['java'],
  js: ['javascript'],
  json: ['json', 'jsonc', 'json5'],
  jsx: ['javascriptreact'],
  julia: ['julia', 'juliamarkdown'],
  markdown: ['markdown', 'mdc'],
  pdf: ['pdf'],
  php: ['php'],
  powershell: ['powershell'],
  properties: ['makefile', 'ini', 'properties'],
  python: ['python'],
  r: ['r'],
  rust: ['rust'],
  sass: ['sass', 'scss'],
  shader: ['hlsl'],
  spreadsheet: ['csv', 'tsv', 'psv'],
  svelte: ['svelte'],
  svg: ['svg'],
  tex: ['bibtex', 'bibtex-style', 'tex', 'doctex', 'latex', 'latex-expl3'],
  text: ['plaintext'],
  toml: ['toml'],
  ts: ['typescript'],
  tsx: ['typescriptreact'],
  vlang: ['v'],
  vstudio: ['vb'],
  vue: [
    'vue',
    'vue-postcss',
    'vue-html',
    'vue-directives',
    'vue-injection-markdown',
    'vue-interpolations',
    'vue-sfc-style-variable-injection',
  ],
  xml: ['xml', 'xquery', 'xsl'],
  yaml: ['yaml'],
}
